# Generated by Django 3.1.2 on 2020-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20201102_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='url',
            new_name='init_url',
        ),
        migrations.AddField(
            model_name='urls',
            name='short_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
