# Generated by Django 3.1.2 on 2020-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20201102_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='init_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.URLField(),
        ),
    ]
